-- CreateTable
CREATE TABLE "PokemonGo" (
    "Row" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT,
    "PokedexNumber" INTEGER,
    "ImgName" TEXT,
    "Generation" INTEGER,
    "EvolutionStage" TEXT,
    "Evolved" INTEGER,
    "FamilyID" INTEGER,
    "CrossGen" BOOLEAN,
    "Type1" TEXT,
    "Type2" TEXT,
    "Weather1" TEXT,
    "Weather2" TEXT,
    "ATK" INTEGER,
    "DEF" INTEGER,
    "STA" INTEGER,
    "Legendary" INTEGER,
    "Aquireable" INTEGER,
    "Spawns" BOOLEAN,
    "Regional" BOOLEAN,
    "Raidable" INTEGER,
    "Hatchable" INTEGER,
    "Shiny" BOOLEAN,
    "Nest" BOOLEAN,
    "New" BOOLEAN,
    "FutureEvolve" BOOLEAN,
    "StatsTotal" INTEGER,
    "NotGettable" BOOLEAN,
    "CP40" INTEGER,
    "CP39" INTEGER
);
