import * as mongoose from 'mongoose';

export const PokemonSchema = new mongoose.Schema({
  name: String,
  pokedexNumber: Number,
  imgName: Number,
  generation: Number,
  evolutionStage: Number,
  evolved: Number,
  familyID: Number,
  crossGen: Number,
  typeOne: String,
  typewo: String,
  weatherOne: String,
  weatherTwo: String,
  statTotal: Number,
  atk: Number,
  def: Number,
  sta: Number,
  legendary: Number,
  aquireable: Number,
  spawns: Number,
  regional: Number,
  raidable: Number,
  hatchable: Number,
  shiny: Number,
  nest: Number,
  new: Number,
  notGettable: Number,
  futureEvolve: Number,
  oneHundredPercentCpForty: Number,
  oneHundredPercentCpThirtyNine: Number,
});