import { Pokemon } from "@prisma/client";

export const POKEMON_DATA: Pokemon[] = [
  {
    id: 1,
    name: "Bulbasaur",
    evolutionStage: 1,
    type1: "grass",
    type2: "poison",
    statsTotal: 326,
    atk: 118,
    def: 118,
    sta: 90,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 2,
    name: "Ivysaur",
    evolutionStage: 2,
    type1: "grass",
    type2: "poison",
    statsTotal: 422,
    atk: 151,
    def: 151,
    sta: 120,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 3,
    name: "Venusaur",
    evolutionStage: 3,
    type1: "grass",
    type2: "poison",
    statsTotal: 556,
    atk: 198,
    def: 198,
    sta: 160,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 4,
    name: "Charmander",
    isEvolved: false,
    type1: "fire",
    type2: null,
    statsTotal: 290,
    atk: 116,
    def: 96,
    sta: 78,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 5,
    name: "Charmeleon",
    isEvolved: false,
    type1: "fire",
    type2: null,
    statsTotal: 403,
    atk: 158,
    def: 129,
    sta: 116,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 6,
    name: "Charizard",
    evolutionStage: 3,
    type1: "fire",
    type2: "flying",
    statsTotal: 555,
    atk: 223,
    def: 176,
    sta: 156,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 7,
    name: "Squirtle",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 304,
    atk: 94,
    def: 122,
    sta: 88,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 8,
    name: "Wartortle",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 399,
    atk: 126,
    def: 155,
    sta: 118,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 9,
    name: "Blastoise",
    isEvolved: true,
    type1: "water",
    type2: null,
    statsTotal: 539,
    atk: 171,
    def: 210,
    sta: 158,
    isLegendary: false,
    evolutionStage: 3,
  },
  {
    id: 10,
    name: "Caterpie",
    isEvolved: false,
    type1: "bug",
    type2: null,
    statsTotal: 207,
    atk: 55,
    def: 62,
    sta: 90,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 11,
    name: "Metapod",
    isEvolved: false,
    type1: "bug",
    type2: null,
    statsTotal: 239,
    atk: 45,
    def: 94,
    sta: 100,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 12,
    name: "Butterfree",
    evolutionStage: 3,
    type1: "bug",
    type2: "flying",
    statsTotal: 438,
    atk: 167,
    def: 151,
    sta: 120,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 13,
    name: "Weedle",
    evolutionStage: 1,
    type1: "bug",
    type2: "poison",
    statsTotal: 198,
    atk: 63,
    def: 55,
    sta: 80,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 14,
    name: "Kakuna",
    evolutionStage: 2,
    type1: "bug",
    type2: "poison",
    statsTotal: 222,
    atk: 46,
    def: 86,
    sta: 90,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 15,
    name: "Beedrill",
    evolutionStage: 3,
    type1: "bug",
    type2: "poison",
    statsTotal: 449,
    atk: 169,
    def: 150,
    sta: 130,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 16,
    name: "Pidgey",
    evolutionStage: 1,
    type1: "normal",
    type2: "flying",
    statsTotal: 241,
    atk: 85,
    def: 76,
    sta: 80,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 17,
    name: "Pidgeotto",
    evolutionStage: 2,
    type1: "normal",
    type2: "flying",
    statsTotal: 351,
    atk: 117,
    def: 108,
    sta: 126,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 18,
    name: "Pidgeot",
    evolutionStage: 3,
    type1: "normal",
    type2: "flying",
    statsTotal: 489,
    atk: 166,
    def: 157,
    sta: 166,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 19,
    name: "Rattata",
    isEvolved: false,
    type1: "normal",
    type2: null,
    statsTotal: 233,
    atk: 103,
    def: 70,
    sta: 60,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 20,
    name: "Raticate",
    isEvolved: false,
    type1: "normal",
    type2: null,
    statsTotal: 415,
    atk: 161,
    def: 144,
    sta: 110,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 21,
    name: "Spearow",
    evolutionStage: 1,
    type1: "normal",
    type2: "flying",
    statsTotal: 253,
    atk: 112,
    def: 61,
    sta: 80,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 22,
    name: "Fearow",
    evolutionStage: 2,
    type1: "normal",
    type2: "flying",
    statsTotal: 447,
    atk: 182,
    def: 135,
    sta: 130,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 23,
    name: "Ekans",
    isEvolved: false,
    type1: "poison",
    type2: null,
    statsTotal: 282,
    atk: 110,
    def: 102,
    sta: 70,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 24,
    name: "Arbok",
    isEvolved: true,
    type1: "poison",
    type2: null,
    statsTotal: 445,
    atk: 167,
    def: 158,
    sta: 120,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 25,
    name: "Pikachu",
    isEvolved: false,
    type1: "electric",
    type2: null,
    statsTotal: 283,
    atk: 112,
    def: 101,
    sta: 70,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 26,
    name: "Raichu",
    isEvolved: true,
    type1: "electric",
    type2: null,
    statsTotal: 478,
    atk: 193,
    def: 165,
    sta: 120,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 27,
    name: "Sandshrew",
    isEvolved: false,
    type1: "ground",
    type2: null,
    statsTotal: 371,
    atk: 126,
    def: 145,
    sta: 100,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 28,
    name: "Sandslash",
    isEvolved: true,
    type1: "ground",
    type2: null,
    statsTotal: 534,
    atk: 182,
    def: 202,
    sta: 150,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 29,
    name: "Nidoran F",
    isEvolved: false,
    type1: "poison",
    type2: null,
    statsTotal: 290,
    atk: 86,
    def: 94,
    sta: 110,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 30,
    name: "Nidorina",
    isEvolved: false,
    type1: "poison",
    type2: null,
    statsTotal: 383,
    atk: 117,
    def: 126,
    sta: 140,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 31,
    name: "Nidoqueen",
    evolutionStage: 3,
    type1: "poison",
    type2: "ground",
    statsTotal: 534,
    atk: 180,
    def: 174,
    sta: 180,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 32,
    name: "Nidoran M",
    isEvolved: false,
    type1: "poison",
    type2: null,
    statsTotal: 273,
    atk: 105,
    def: 76,
    sta: 92,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 33,
    name: "Nidorino",
    isEvolved: false,
    type1: "poison",
    type2: null,
    statsTotal: 371,
    atk: 137,
    def: 112,
    sta: 122,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 34,
    name: "Nidoking",
    evolutionStage: 3,
    type1: "poison",
    type2: "ground",
    statsTotal: 523,
    atk: 204,
    def: 157,
    sta: 162,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 35,
    name: "Clefairy",
    isEvolved: false,
    type1: "fairy",
    type2: null,
    statsTotal: 363,
    atk: 107,
    def: 116,
    sta: 140,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 36,
    name: "Clefable",
    isEvolved: true,
    type1: "fairy",
    type2: null,
    statsTotal: 539,
    atk: 178,
    def: 171,
    sta: 190,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 37,
    name: "Vulpix",
    isEvolved: false,
    type1: "fire",
    type2: null,
    statsTotal: 294,
    atk: 96,
    def: 122,
    sta: 76,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 38,
    name: "Ninetales",
    isEvolved: true,
    type1: "fire",
    type2: null,
    statsTotal: 519,
    atk: 169,
    def: 204,
    sta: 146,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 39,
    name: "Jigglypuff",
    evolutionStage: 1,
    type1: "normal",
    type2: "fairy",
    statsTotal: 354,
    atk: 80,
    def: 44,
    sta: 230,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 40,
    name: "Wigglytuff",
    evolutionStage: 2,
    type1: "normal",
    type2: "fairy",
    statsTotal: 529,
    atk: 156,
    def: 93,
    sta: 280,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 41,
    name: "Zubat",
    evolutionStage: 1,
    type1: "poison",
    type2: "flying",
    statsTotal: 239,
    atk: 83,
    def: 76,
    sta: 80,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 42,
    name: "Golbat",
    evolutionStage: 2,
    type1: "poison",
    type2: "flying",
    statsTotal: 464,
    atk: 161,
    def: 153,
    sta: 150,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 43,
    name: "Oddish",
    evolutionStage: 1,
    type1: "grass",
    type2: "poison",
    statsTotal: 337,
    atk: 131,
    def: 116,
    sta: 90,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 44,
    name: "Gloom",
    evolutionStage: 2,
    type1: "grass",
    type2: "poison",
    statsTotal: 412,
    atk: 153,
    def: 139,
    sta: 120,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 45,
    name: "Vileplume",
    evolutionStage: 3,
    type1: "grass",
    type2: "poison",
    statsTotal: 522,
    atk: 202,
    def: 170,
    sta: 150,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 46,
    name: "Paras",
    evolutionStage: 1,
    type1: "bug",
    type2: "grass",
    statsTotal: 290,
    atk: 121,
    def: 99,
    sta: 70,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 47,
    name: "Parasect",
    evolutionStage: 2,
    type1: "bug",
    type2: "grass",
    statsTotal: 431,
    atk: 165,
    def: 146,
    sta: 120,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 48,
    name: "Venonat",
    evolutionStage: 1,
    type1: "bug",
    type2: "poison",
    statsTotal: 322,
    atk: 100,
    def: 102,
    sta: 120,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 49,
    name: "Venomoth",
    evolutionStage: 2,
    type1: "bug",
    type2: "poison",
    statsTotal: 469,
    atk: 179,
    def: 150,
    sta: 140,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 50,
    name: "Diglett",
    isEvolved: false,
    type1: "ground",
    type2: null,
    statsTotal: 217,
    atk: 109,
    def: 88,
    sta: 20,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 51,
    name: "Dugtrio",
    isEvolved: true,
    type1: "ground",
    type2: null,
    statsTotal: 384,
    atk: 167,
    def: 147,
    sta: 70,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 52,
    name: "Meowth",
    isEvolved: false,
    type1: "normal",
    type2: null,
    statsTotal: 253,
    atk: 92,
    def: 81,
    sta: 80,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 53,
    name: "Persian",
    isEvolved: true,
    type1: "normal",
    type2: null,
    statsTotal: 419,
    atk: 150,
    def: 139,
    sta: 130,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 54,
    name: "Psyduck",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 318,
    atk: 122,
    def: 96,
    sta: 100,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 55,
    name: "Golduck",
    isEvolved: true,
    type1: "water",
    type2: null,
    statsTotal: 514,
    atk: 191,
    def: 163,
    sta: 160,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 56,
    name: "Mankey",
    isEvolved: false,
    type1: "fighting",
    type2: null,
    statsTotal: 315,
    atk: 148,
    def: 87,
    sta: 80,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 57,
    name: "Primeape",
    isEvolved: true,
    type1: "fighting",
    type2: null,
    statsTotal: 481,
    atk: 207,
    def: 144,
    sta: 130,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 58,
    name: "Growlithe",
    isEvolved: false,
    type1: "fire",
    type2: null,
    statsTotal: 342,
    atk: 136,
    def: 96,
    sta: 110,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 59,
    name: "Arcanine",
    isEvolved: true,
    type1: "fire",
    type2: null,
    statsTotal: 573,
    atk: 227,
    def: 166,
    sta: 180,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 60,
    name: "Poliwag",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 263,
    atk: 101,
    def: 82,
    sta: 80,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 61,
    name: "Poliwhirl",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 390,
    atk: 130,
    def: 130,
    sta: 130,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 62,
    name: "Poliwrath",
    evolutionStage: 3,
    type1: "water",
    type2: "fighting",
    statsTotal: 549,
    atk: 182,
    def: 187,
    sta: 180,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 63,
    name: "Abra",
    isEvolved: false,
    type1: "psychic",
    type2: null,
    statsTotal: 348,
    atk: 195,
    def: 103,
    sta: 50,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 64,
    name: "Kadabra",
    isEvolved: false,
    type1: "psychic",
    type2: null,
    statsTotal: 450,
    atk: 232,
    def: 138,
    sta: 80,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 65,
    name: "Alakazam",
    isEvolved: true,
    type1: "psychic",
    type2: null,
    statsTotal: 575,
    atk: 271,
    def: 194,
    sta: 110,
    isLegendary: false,
    evolutionStage: 3,
  },
  {
    id: 66,
    name: "Machop",
    isEvolved: false,
    type1: "fighting",
    type2: null,
    statsTotal: 365,
    atk: 137,
    def: 88,
    sta: 140,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 67,
    name: "Machoke",
    isEvolved: false,
    type1: "fighting",
    type2: null,
    statsTotal: 467,
    atk: 177,
    def: 130,
    sta: 160,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 68,
    name: "Machamp",
    isEvolved: true,
    type1: "fighting",
    type2: null,
    statsTotal: 576,
    atk: 234,
    def: 162,
    sta: 180,
    isLegendary: false,
    evolutionStage: 3,
  },
  {
    id: 69,
    name: "Bellsprout",
    evolutionStage: 1,
    type1: "grass",
    type2: "poison",
    statsTotal: 303,
    atk: 139,
    def: 64,
    sta: 100,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 70,
    name: "Weepinbell",
    evolutionStage: 2,
    type1: "grass",
    type2: "poison",
    statsTotal: 397,
    atk: 172,
    def: 95,
    sta: 130,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 71,
    name: "Victreebel",
    evolutionStage: 3,
    type1: "grass",
    type2: "poison",
    statsTotal: 505,
    atk: 207,
    def: 138,
    sta: 160,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 72,
    name: "Tentacool",
    evolutionStage: 1,
    type1: "water",
    type2: "poison",
    statsTotal: 359,
    atk: 97,
    def: 182,
    sta: 80,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 73,
    name: "Tentacruel",
    evolutionStage: 2,
    type1: "water",
    type2: "poison",
    statsTotal: 563,
    atk: 166,
    def: 237,
    sta: 160,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 74,
    name: "Geodude",
    evolutionStage: 1,
    type1: "rock",
    type2: "ground",
    statsTotal: 375,
    atk: 132,
    def: 163,
    sta: 80,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 75,
    name: "Graveler",
    evolutionStage: 2,
    type1: "rock",
    type2: "ground",
    statsTotal: 470,
    atk: 164,
    def: 196,
    sta: 110,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 76,
    name: "Golem",
    evolutionStage: 3,
    type1: "rock",
    type2: "ground",
    statsTotal: 600,
    atk: 211,
    def: 229,
    sta: 160,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 77,
    name: "Ponyta",
    isEvolved: false,
    type1: "fire",
    type2: null,
    statsTotal: 402,
    atk: 170,
    def: 132,
    sta: 100,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 78,
    name: "Rapidash",
    isEvolved: true,
    type1: "fire",
    type2: null,
    statsTotal: 504,
    atk: 207,
    def: 167,
    sta: 130,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 79,
    name: "Slowpoke",
    evolutionStage: 1,
    type1: "water",
    type2: "psychic",
    statsTotal: 398,
    atk: 109,
    def: 109,
    sta: 180,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 80,
    name: "Slowbro",
    evolutionStage: 2,
    type1: "water",
    type2: "psychic",
    statsTotal: 561,
    atk: 177,
    def: 194,
    sta: 190,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 81,
    name: "Magnemite",
    evolutionStage: 1,
    type1: "electric",
    type2: "steel",
    statsTotal: 343,
    atk: 165,
    def: 128,
    sta: 50,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 82,
    name: "Magneton",
    evolutionStage: 2,
    type1: "electric",
    type2: "steel",
    statsTotal: 505,
    atk: 223,
    def: 182,
    sta: 100,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 83,
    name: "Farfetchd",
    evolutionStage: 1,
    type1: "normal",
    type2: "flying",
    statsTotal: 346,
    atk: 124,
    def: 118,
    sta: 104,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 84,
    name: "Doduo",
    evolutionStage: 1,
    type1: "normal",
    type2: "flying",
    statsTotal: 316,
    atk: 158,
    def: 88,
    sta: 70,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 85,
    name: "Dodrio",
    evolutionStage: 2,
    type1: "normal",
    type2: "flying",
    statsTotal: 483,
    atk: 218,
    def: 145,
    sta: 120,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 86,
    name: "Seel",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 343,
    atk: 85,
    def: 128,
    sta: 130,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 87,
    name: "Dewgong",
    evolutionStage: 2,
    type1: "water",
    type2: "ice",
    statsTotal: 503,
    atk: 139,
    def: 184,
    sta: 180,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 88,
    name: "Grimer",
    isEvolved: false,
    type1: "poison",
    type2: null,
    statsTotal: 385,
    atk: 135,
    def: 90,
    sta: 160,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 89,
    name: "Muk",
    isEvolved: true,
    type1: "poison",
    type2: null,
    statsTotal: 584,
    atk: 190,
    def: 184,
    sta: 210,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 90,
    name: "Shellder",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 344,
    atk: 116,
    def: 168,
    sta: 60,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 91,
    name: "Cloyster",
    evolutionStage: 2,
    type1: "water",
    type2: "ice",
    statsTotal: 609,
    atk: 186,
    def: 323,
    sta: 100,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 92,
    name: "Gastly",
    evolutionStage: 1,
    type1: "ghost",
    type2: "poison",
    statsTotal: 316,
    atk: 186,
    def: 70,
    sta: 60,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 93,
    name: "Haunter",
    evolutionStage: 2,
    type1: "ghost",
    type2: "poison",
    statsTotal: 425,
    atk: 223,
    def: 112,
    sta: 90,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 94,
    name: "Gengar",
    evolutionStage: 3,
    type1: "ghost",
    type2: "poison",
    statsTotal: 537,
    atk: 261,
    def: 156,
    sta: 120,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 95,
    name: "Onix",
    evolutionStage: 1,
    type1: "rock",
    type2: "ground",
    statsTotal: 443,
    atk: 85,
    def: 288,
    sta: 70,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 96,
    name: "Drowzee",
    isEvolved: false,
    type1: "psychic",
    type2: null,
    statsTotal: 367,
    atk: 89,
    def: 158,
    sta: 120,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 97,
    name: "Hypno",
    isEvolved: true,
    type1: "psychic",
    type2: null,
    statsTotal: 529,
    atk: 144,
    def: 215,
    sta: 170,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 98,
    name: "Krabby",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 397,
    atk: 181,
    def: 156,
    sta: 60,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 99,
    name: "Kingler",
    isEvolved: true,
    type1: "water",
    type2: null,
    statsTotal: 564,
    atk: 240,
    def: 214,
    sta: 110,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 100,
    name: "Voltorb",
    isEvolved: false,
    type1: "electric",
    type2: null,
    statsTotal: 303,
    atk: 109,
    def: 114,
    sta: 80,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 101,
    name: "Electrode",
    isEvolved: true,
    type1: "electric",
    type2: null,
    statsTotal: 472,
    atk: 173,
    def: 179,
    sta: 120,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 102,
    name: "Exeggcute",
    evolutionStage: 1,
    type1: "grass",
    type2: "psychic",
    statsTotal: 367,
    atk: 107,
    def: 140,
    sta: 120,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 103,
    name: "Exeggutor",
    evolutionStage: 2,
    type1: "grass",
    type2: "psychic",
    statsTotal: 581,
    atk: 233,
    def: 158,
    sta: 190,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 104,
    name: "Cubone",
    isEvolved: false,
    type1: "ground",
    type2: null,
    statsTotal: 355,
    atk: 90,
    def: 165,
    sta: 100,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 105,
    name: "Marowak",
    isEvolved: true,
    type1: "ground",
    type2: null,
    statsTotal: 464,
    atk: 144,
    def: 200,
    sta: 120,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 106,
    name: "Hitmonlee",
    isEvolved: true,
    type1: "fighting",
    type2: null,
    statsTotal: 535,
    atk: 224,
    def: 211,
    sta: 100,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 107,
    name: "Hitmonchan",
    isEvolved: true,
    type1: "fighting",
    type2: null,
    statsTotal: 505,
    atk: 193,
    def: 212,
    sta: 100,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 108,
    name: "Lickitung",
    isEvolved: true,
    type1: "normal",
    type2: null,
    statsTotal: 425,
    atk: 108,
    def: 137,
    sta: 180,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 109,
    name: "Koffing",
    isEvolved: false,
    type1: "poison",
    type2: null,
    statsTotal: 363,
    atk: 119,
    def: 164,
    sta: 80,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 110,
    name: "Weezing",
    isEvolved: true,
    type1: "poison",
    type2: null,
    statsTotal: 525,
    atk: 174,
    def: 221,
    sta: 130,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 111,
    name: "Rhyhorn",
    evolutionStage: 1,
    type1: "ground",
    type2: "rock",
    statsTotal: 457,
    atk: 140,
    def: 157,
    sta: 160,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 112,
    name: "Rhydon",
    evolutionStage: 2,
    type1: "ground",
    type2: "rock",
    statsTotal: 638,
    atk: 222,
    def: 206,
    sta: 210,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 113,
    name: "Chansey",
    isEvolved: false,
    type1: "normal",
    type2: null,
    statsTotal: 736,
    atk: 60,
    def: 176,
    sta: 500,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 114,
    name: "Tangela",
    isEvolved: true,
    type1: "grass",
    type2: null,
    statsTotal: 518,
    atk: 183,
    def: 205,
    sta: 130,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 115,
    name: "Kangaskhan",
    isEvolved: true,
    type1: "normal",
    type2: null,
    statsTotal: 556,
    atk: 181,
    def: 165,
    sta: 210,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 116,
    name: "Horsea",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 314,
    atk: 129,
    def: 125,
    sta: 60,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 117,
    name: "Seadra",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 479,
    atk: 187,
    def: 182,
    sta: 110,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 118,
    name: "Goldeen",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 328,
    atk: 123,
    def: 115,
    sta: 90,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 119,
    name: "Seaking",
    isEvolved: true,
    type1: "water",
    type2: null,
    statsTotal: 489,
    atk: 175,
    def: 154,
    sta: 160,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 120,
    name: "Staryu",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 309,
    atk: 137,
    def: 112,
    sta: 60,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 121,
    name: "Starmie",
    evolutionStage: 2,
    type1: "water",
    type2: "psychic",
    statsTotal: 514,
    atk: 210,
    def: 184,
    sta: 120,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 122,
    name: "Mr Mime",
    evolutionStage: 1,
    type1: "psychic",
    type2: "fairy",
    statsTotal: 505,
    atk: 192,
    def: 233,
    sta: 80,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 123,
    name: "Scyther",
    evolutionStage: 1,
    type1: "bug",
    type2: "flying",
    statsTotal: 528,
    atk: 218,
    def: 170,
    sta: 140,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 124,
    name: "Jynx",
    evolutionStage: 1,
    type1: "ice",
    type2: "psychic",
    statsTotal: 535,
    atk: 223,
    def: 182,
    sta: 130,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 125,
    name: "Electabuzz",
    isEvolved: true,
    type1: "electric",
    type2: null,
    statsTotal: 501,
    atk: 198,
    def: 173,
    sta: 130,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 126,
    name: "Magmar",
    isEvolved: true,
    type1: "fire",
    type2: null,
    statsTotal: 505,
    atk: 206,
    def: 169,
    sta: 130,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 127,
    name: "Pinsir",
    isEvolved: true,
    type1: "bug",
    type2: null,
    statsTotal: 565,
    atk: 238,
    def: 197,
    sta: 130,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 128,
    name: "Tauros",
    isEvolved: true,
    type1: "normal",
    type2: null,
    statsTotal: 545,
    atk: 198,
    def: 197,
    sta: 150,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 129,
    name: "Magikarp",
    isEvolved: false,
    type1: "water",
    type2: null,
    statsTotal: 171,
    atk: 29,
    def: 102,
    sta: 40,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 130,
    name: "Gyarados",
    evolutionStage: 2,
    type1: "water",
    type2: "flying",
    statsTotal: 624,
    atk: 237,
    def: 197,
    sta: 190,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 131,
    name: "Lapras",
    evolutionStage: 1,
    type1: "water",
    type2: "ice",
    statsTotal: 605,
    atk: 165,
    def: 180,
    sta: 260,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 132,
    name: "Ditto",
    isEvolved: false,
    type1: "normal",
    type2: null,
    statsTotal: 278,
    atk: 91,
    def: 91,
    sta: 96,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 133,
    name: "Eevee",
    isEvolved: false,
    type1: "normal",
    type2: null,
    statsTotal: 335,
    atk: 104,
    def: 121,
    sta: 110,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 134,
    name: "Vaporeon",
    isEvolved: true,
    type1: "water",
    type2: null,
    statsTotal: 642,
    atk: 205,
    def: 177,
    sta: 260,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 135,
    name: "Jolteon",
    isEvolved: true,
    type1: "electric",
    type2: null,
    statsTotal: 563,
    atk: 232,
    def: 201,
    sta: 130,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 136,
    name: "Flareon",
    isEvolved: true,
    type1: "fire",
    type2: null,
    statsTotal: 580,
    atk: 246,
    def: 204,
    sta: 130,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 137,
    name: "Porygon",
    isEvolved: false,
    type1: "normal",
    type2: null,
    statsTotal: 422,
    atk: 153,
    def: 139,
    sta: 130,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 138,
    name: "Omanyte",
    evolutionStage: 1,
    type1: "rock",
    type2: "water",
    statsTotal: 399,
    atk: 155,
    def: 174,
    sta: 70,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 139,
    name: "Omastar",
    evolutionStage: 2,
    type1: "rock",
    type2: "water",
    statsTotal: 574,
    atk: 207,
    def: 227,
    sta: 140,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 140,
    name: "Kabuto",
    evolutionStage: 1,
    type1: "rock",
    type2: "water",
    statsTotal: 370,
    atk: 148,
    def: 162,
    sta: 60,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 141,
    name: "Kabutops",
    evolutionStage: 2,
    type1: "rock",
    type2: "water",
    statsTotal: 543,
    atk: 220,
    def: 203,
    sta: 120,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 142,
    name: "Aerodactyl",
    evolutionStage: 1,
    type1: "rock",
    type2: "flying",
    statsTotal: 545,
    atk: 221,
    def: 164,
    sta: 160,
    isLegendary: false,
    isEvolved: false,
  },
  {
    id: 143,
    name: "Snorlax",
    isEvolved: false,
    type1: "normal",
    type2: null,
    statsTotal: 700,
    atk: 190,
    def: 190,
    sta: 320,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 144,
    name: "Articuno",
    evolutionStage: 1,
    type1: "ice",
    type2: "flying",
    statsTotal: 621,
    atk: 192,
    def: 249,
    sta: 180,
    isLegendary: true,
    isEvolved: false,
  },
  {
    id: 145,
    name: "Zapdos",
    evolutionStage: 1,
    type1: "electric",
    type2: "flying",
    statsTotal: 621,
    atk: 253,
    def: 188,
    sta: 180,
    isLegendary: true,
    isEvolved: false,
  },
  {
    id: 146,
    name: "Moltres",
    evolutionStage: 1,
    type1: "fire",
    type2: "flying",
    statsTotal: 615,
    atk: 251,
    def: 184,
    sta: 180,
    isLegendary: true,
    isEvolved: false,
  },
  {
    id: 147,
    name: "Dratini",
    isEvolved: false,
    type1: "dragon",
    type2: null,
    statsTotal: 295,
    atk: 119,
    def: 94,
    sta: 82,
    isLegendary: false,
    evolutionStage: 1,
  },
  {
    id: 148,
    name: "Dragonair",
    isEvolved: true,
    type1: "dragon",
    type2: null,
    statsTotal: 423,
    atk: 163,
    def: 138,
    sta: 122,
    isLegendary: false,
    evolutionStage: 2,
  },
  {
    id: 149,
    name: "Dragonite",
    evolutionStage: 3,
    type1: "dragon",
    type2: "flying",
    statsTotal: 646,
    atk: 263,
    def: 201,
    sta: 182,
    isLegendary: false,
    isEvolved: true,
  },
  {
    id: 150,
    name: "Mewtwo",
    isEvolved: false,
    type1: "psychic",
    type2: null,
    statsTotal: 675,
    atk: 300,
    def: 182,
    sta: 193,
    isLegendary: true,
    evolutionStage: 1,
  },
  {
    id: 151,
    name: "Mew",
    isEvolved: true,
    type1: "psychic",
    type2: null,
    statsTotal: 620,
    atk: 210,
    def: 210,
    sta: 200,
    isLegendary: false,
    evolutionStage: 1,
  },
];
