export type Pokemon = {
  id: string
  Name: string
  PokedexNumber: number
  ImgName: number
  Generation: number
  EvolutionStage: number
  Evolved: number
  FamilyID: number
  CrossGen: number
  Type1: string
  Type2: string
  Weather1: string
  Weather2: string
  STATTOTAL: number
  ATK: number
  DEF: number
  STA: number
  Legendary: number
  Aquireable: number
  Spawns: number
  Regional: number
  Raidable: number
  Hatchable: number
  Shiny: number
  Nest: number
  New: number
  NotGettable: number
  FutureEvolve: number
  CP40: number
  CP39: number
}
