export const pokemons = [
    {
        "Row": "1",
        "Name": "Bulbasaur",
        "Pokedex Number": "1",
        "Img name": "1",
        "Generation": "1",
        "Evolution Stage": "1",
        "Evolved": "0",
        "FamilyID": "1",
        "Cross Gen": "0",
        "Type 1": "grass",
        "Type 2": "poison",
        "Weather 1": "Sunny/clear",
        "Weather 2": "Cloudy",
        "STAT TOTAL": "326",
        "ATK": "118",
        "DEF": "118",
        "STA": "90",
        "Legendary": "0",
        "Aquireable": "1",
        "Spawns": "1",
        "Regional": "0",
        "Raidable": "0",
        "Hatchable": "5",
        "Shiny": "0",
        "Nest": "1",
        "New": "0",
        "Not-Gettable": "0",
        "Future Evolve": "0",
        "100% CP @ 40": "981",
        "100% CP @ 39": "967"
    },
    {
        "Row": "2",
        "Name": "Ivysaur",
        "Pokedex Number": "2",
        "Img name": "2",
        "Generation": "1",
        "Evolution Stage": "2",
        "Evolved": "0",
        "FamilyID": "1",
        "Cross Gen": "0",
        "Type 1": "grass",
        "Type 2": "poison",
        "Weather 1": "Sunny/clear",
        "Weather 2": "Cloudy",
        "STAT TOTAL": "422",
        "ATK": "151",
        "DEF": "151",
        "STA": "120",
        "Legendary": "0",
        "Aquireable": "1",
        "Spawns": "1",
        "Regional": "0",
        "Raidable": "0",
        "Hatchable": "0",
        "Shiny": "0",
        "Nest": "0",
        "New": "0",
        "Not-Gettable": "0",
        "Future Evolve": "0",
        "100% CP @ 40": "1552",
        "100% CP @ 39": "1529"
    },
    {
        "Row": "3",
        "Name": "Venusaur",
        "Pokedex Number": "3",
        "Img name": "3",
        "Generation": "1",
        "Evolution Stage": "3",
        "Evolved": "1",
        "FamilyID": "1",
        "Cross Gen": "0",
        "Type 1": "grass",
        "Type 2": "poison",
        "Weather 1": "Sunny/clear",
        "Weather 2": "Cloudy",
        "STAT TOTAL": "556",
        "ATK": "198",
        "DEF": "198",
        "STA": "160",
        "Legendary": "0",
        "Aquireable": "1",
        "Spawns": "1",
        "Regional": "0",
        "Raidable": "0",
        "Hatchable": "0",
        "Shiny": "0",
        "Nest": "0",
        "New": "0",
        "Not-Gettable": "0",
        "Future Evolve": "0",
        "100% CP @ 40": "2568",
        "100% CP @ 39": "2531"
    },
    {
        "Row": "4",
        "Name": "Charmander",
        "Pokedex Number": "4",
        "Img name": "4",
        "Generation": "1",
        "Evolution Stage": "1",
        "Evolved": "0",
        "FamilyID": "2",
        "Cross Gen": "0",
        "Type 1": "fire",
        "Weather 1": "Sunny/clear",
        "STAT TOTAL": "290",
        "ATK": "116",
        "DEF": "96",
        "STA": "78",
        "Legendary": "0",
        "Aquireable": "1",
        "Spawns": "1",
        "Regional": "0",
        "Raidable": "0",
        "Hatchable": "5",
        "Shiny": "0",
        "Nest": "1",
        "New": "0",
        "Not-Gettable": "0",
        "Future Evolve": "0",
        "100% CP @ 40": "831",
        "100% CP @ 39": "819"
    },
    {
        "Row": "5",
        "Name": "Charmeleon",
        "Pokedex Number": "5",
        "Img name": "5",
        "Generation": "1",
        "Evolution Stage": "2",
        "Evolved": "0",
        "FamilyID": "2",
        "Cross Gen": "0",
        "Type 1": "fire",
        "Weather 1": "Sunny/clear",
        "STAT TOTAL": "403",
        "ATK": "158",
        "DEF": "129",
        "STA": "116",
        "Legendary": "0",
        "Aquireable": "1",
        "Spawns": "1",
        "Regional": "0",
        "Raidable": "0",
        "Hatchable": "0",
        "Shiny": "0",
        "Nest": "0",
        "New": "0",
        "Not-Gettable": "0",
        "Future Evolve": "0",
        "100% CP @ 40": "1484",
        "100% CP @ 39": "1462"
    },
    {
        "Row": "6",
        "Name": "Charizard",
        "Pokedex Number": "6",
        "Img name": "6",
        "Generation": "1",
        "Evolution Stage": "3",
        "Evolved": "1",
        "FamilyID": "2",
        "Cross Gen": "0",
        "Type 1": "fire",
        "Type 2": "flying",
        "Weather 1": "Sunny/clear",
        "Weather 2": "Windy",
        "STAT TOTAL": "555",
        "ATK": "223",
        "DEF": "176",
        "STA": "156",
        "Legendary": "0",
        "Aquireable": "1",
        "Spawns": "1",
        "Regional": "0",
        "Raidable": "0",
        "Hatchable": "0",
        "Shiny": "0",
        "Nest": "0",
        "New": "0",
        "Not-Gettable": "0",
        "Future Evolve": "0",
        "100% CP @ 40": "2686",
        "100% CP @ 39": "2648"
    }
]